# Generated by Django 3.2.16 on 2023-03-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20230222_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.ImageField(blank=True, default='default-image.png', null=True, upload_to=''),
        ),
    ]
