# Generated by Django 3.2.16 on 2023-03-01 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='email',
            new_name='address',
        ),
    ]
