# Generated by Django 3.2.16 on 2023-03-08 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(default='No Publisher', on_delete=django.db.models.deletion.CASCADE, to='books.publisher'),
        ),
    ]
